image: node:8-alpine

stages:
  - test
  - deploy

### TEST: ###
install_packages_and_run_lint:
  stage: test
  script:
    - npm install
    - npm run lint
  artifacts:
    expire_in: 2 days
    paths:
      # we will need the installed packages in next step, so cache might not be enough - we need to create an artifact:
      - ./node_modules

publish_to_npm:
  stage: deploy
  when: manual
  variables:
    NPMJS_REGISTRY: registry.npmjs.org
  only:
    variables:
      # We only allow this job to run if there was a tag, starting with
      # "vX.Y.Z". The reason is that we put the version in package.json.
      - $CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+([-]rc[.][a-z0-9_-]+)?$/
  script:
    - npm version --no-git-tag-version "${CI_COMMIT_TAG}"
    - npm run build
    - echo "//${NPMJS_REGISTRY}/:_authToken=${NPMJS_TOKEN}" > .npmrc
    - '[ $(echo "${CI_COMMIT_TAG}" | grep rc) ] && echo "publishing with next tag to npm ${CI_COMMIT_TAG}" || echo "publishing with latest tag to npm"'
    - '[ $(echo "${CI_COMMIT_TAG}" | grep rc) ] && npm publish --access public --tag next || npm publish --access public'
    - 'echo "Published to npm registry: ${NPM_REGISTRY}"'
